Фильтрование новостей по категориям
IvanPozd/health_project pull request #10
Opened 2021-11-02 13:12 UTC by IvanPozd

2021-11-05 15:47 UTC, statz requested changes

2021-11-05 15:47 UTC, statz commented on webapp/news/views.py
> +@blueprint.route("/category_meal")
Нужно сделать train и meal  одной функцией, а уже внутри в зависимости от категории выбирать заголовок и страницу

2021-11-05 15:47 UTC, statz commented on webapp/templates/menu.html
> +          <li class="nav-item">
Может здесь динамически через цикл релизовать категории?

2021-11-05 17:28 UTC, IvanPozd commented on webapp/news/views.py
> +@blueprint.route("/category_meal")
Реализовал.

2021-11-05 17:32 UTC, IvanPozd commented on webapp/templates/menu.html
> +          <li class="nav-item">
подскажи как это реализовать)

2021-11-05 17:57 UTC, statz commented on webapp/templates/menu.html
> +          <li class="nav-item">
https://github.com/IvanPozd/health_project/pull/10/files#diff-7e39be2c910f89e4bb912a192c02f5d4e97ac6bb82b9e42da076c97605d7471fR13 что-то типа такого не получится сделать?

2021-11-11 15:37 UTC, IvanPozd commented on webapp/templates/menu.html
> +          <li class="nav-item">
через цикл чтото у меня не выводит...

2021-11-11 15:52 UTC, merged